// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArI8iINdufI-QYOLGsLWhj9BSZI53HA94',
    appId: '1:287578845685:android:da8ae415ae169cf877b0bc',
    messagingSenderId: '287578845685',
    projectId: 'flutter-apps-1508d',
    storageBucket: 'flutter-apps-1508d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbvATfB0y4bEXM8If89aljgJ1paf7jdQE',
    appId: '1:287578845685:ios:601cd8dc821bc18b77b0bc',
    messagingSenderId: '287578845685',
    projectId: 'flutter-apps-1508d',
    storageBucket: 'flutter-apps-1508d.firebasestorage.app',
    androidClientId:
        '287578845685-mjumjn663eka1eovjklj1uet29j7rrqi.apps.googleusercontent.com',
    iosClientId:
        '287578845685-82e498oq8v6jbvpcdviimt5lkiv2nn8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWalletAppCG',
  );
}
